tavis: add workaround for old mock
Old mock require config path (-r) without extension, which is added
automatically. New mock require the opposite - if full config path is
used it does not try to add .cfg at all. And even tell you about it:

    ERROR: Could not find required config file: /etc/mock//home/user/builder-R4.0/qubes-src/builder-rpm//mock-fedora.cfg
    ERROR:   If you're trying to specify a path, include the .cfg extension, e.g. -r ./target.cfg

Workaround the problem by adding symlinks with double extension, so both
version will find the file.